on:
    push: 
        tags: 
            - 'v*.*.*'

jobs:
    create_release:
        runs-on: ubuntu-latest
        container: 
            image: "node:22-alpine3.19"
        permissions:
          contents: write
        steps:
        - name: Create Release
          uses: ncipollo/release-action@v1
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm run build
        - name: Create tarball
          run: |
            apk update && apk add xz
            tar -Javcf archive.tar -C dist .
        - name: Upload Release Asset
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: archive.tar
            overwrite: false